baseURL = 'https://larryling.github.io/cs397-homework4/'
languageCode = 'en-us'
title = 'Larry Ling'
theme = 'PaperMod'
canonifyURLs = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[menu]
  [[menu.main]]
    name = "Education"
    url = "#education"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 3
  [[menu.main]]
    name = "Skills"
    url = "#skills"
    weight = 4

[params]
  env = "production"
  defaultTheme = "auto"
  disableNavbarTitle = true

[params.label]
  text = ""
  icon = ""
